[package]
name = "blyxc"
version = "0.1.0"
edition = "2024"
description = "Official Compiler Driver for the Blyx Programming Language"

[dependencies]
blyx_lexer = { path = "../blyx_lexer" }
blyx_parser = { path = "../blyx_parser" }
blyx_ast = { path = "../blyx_ast" }
blyx_semantic = { path = "../blyx_semantic" }
blyx_typeck = { path = "../blyx_typeck" }
blyx_bir = { path = "../blyx_bir" }
