"use client";

import React, { useState } from "react";
import Container from "@/components/ui/Container";
import Breadcrumb from "@/components/Breadcrumb";
import dynamic from "next/dynamic";
import { Play, RotateCcw, Copy, Check, Terminal, Layers, Cpu } from "lucide-react";

const MonacoEditor = dynamic(() => import("@monaco-editor/react"), { ssr: false });

const SAMPLES = {
  hello: `fn main() -> i32 {
    println("Hello, Blyx systems language!");
    return 0;
}`,
  tensor: `import std.tensor;

fn main() {
    let a = Tensor::random<f32, [128, 64]>();
    let b = Tensor::random<f32, [64, 32]>();
    let c = matmul(a, b);
    println("Matrix C result shape: {:?}", c.shape);
}`,
  actor: `actor Worker {
    fn receive(msg: Message) {
        match msg {
            Task(id, data) => process(id, data),
            Shutdown => break,
        }
    }
}

fn main() {
    let worker = spawn Worker();
    worker.send(Task(1, [1.0, 2.0, 3.0]));
}`,
};

export default function PlayPage() {
  const [code, setCode] = useState(SAMPLES.hello);
  const [activeTab, setActiveTab] = useState<"output" | "bir" | "llvm">("output");
  const [running, setRunning] = useState(false);
  const [output, setOutput] = useState("Click 'Run Code' to compile and execute.");

  const handleRun = () => {
    setRunning(true);
    setOutput("Compiling with blyx v0.1.0-beta target x86_64-unknown-linux-gnu...\nExecuting BIR SSA optimization passes...\n\nHello, Blyx systems language!\n[Process exited with code 0]");
    setTimeout(() => setRunning(false), 400);
  };

  return (
    <Container size="xl" className="py-8 space-y-6">
      <Breadcrumb items={[{ label: "Playground IDE" }]} />

      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h1 className="font-['IBM_Plex_Sans'] font-bold text-2xl sm:text-3xl text-[var(--text-primary)]">
            Blyx Interactive Playground
          </h1>
          <p className="text-xs text-[var(--text-secondary)] mt-1">
            Compile, run, and inspect BIR SSA & LLVM IR generated by the Blyx compiler.
          </p>
        </div>

        <div className="flex items-center space-x-3">
          <select
            onChange={(e) => setCode(SAMPLES[e.target.value as keyof typeof SAMPLES])}
            className="px-3 py-1.5 rounded-lg border border-[var(--border-color)] bg-[var(--bg-secondary)] text-xs text-[var(--text-primary)] font-mono focus:outline-none"
          >
            <option value="hello">Sample: Hello World</option>
            <option value="tensor">Sample: Tensor Math</option>
            <option value="actor">Sample: Actor Messaging</option>
          </select>
          <button
            onClick={handleRun}
            disabled={running}
            className="px-4 py-1.5 rounded-lg bg-[#0284c7] hover:bg-[#0369a1] text-white font-semibold text-xs flex items-center space-x-1.5 shadow-sm transition-all"
          >
            <Play className="w-3.5 h-3.5 fill-current" />
            <span>{running ? "Compiling..." : "Run Code"}</span>
          </button>
        </div>
      </div>

      {/* Split Pane Editor */}
      <div className="grid lg:grid-cols-12 gap-4 h-[550px] border border-[var(--border-strong)] rounded-xl overflow-hidden bg-[var(--bg-card)] shadow-sm">
        {/* Code Editor */}
        <div className="lg:col-span-7 border-r border-[var(--border-color)] flex flex-col">
          <div className="px-4 py-2 bg-[var(--bg-secondary)] border-b border-[var(--border-color)] text-xs font-mono text-[var(--text-muted)] flex items-center justify-between">
            <span>main.blyx</span>
            <span>Monaco Editor</span>
          </div>
          <div className="flex-1">
            <MonacoEditor
              height="100%"
              language="rust"
              theme="vs-dark"
              value={code}
              onChange={(v: string | undefined) => setCode(v || "")}
              options={{
                fontSize: 13,
                minimap: { enabled: false },
                lineNumbers: "on",
                scrollBeyondLastLine: false,
                fontFamily: "JetBrains Mono",
              }}
            />
          </div>
        </div>

        {/* Output Pane */}
        <div className="lg:col-span-5 flex flex-col bg-[var(--code-bg)] text-[var(--code-text)]">
          {/* Tabs */}
          <div className="flex items-center space-x-1 px-3 py-2 bg-[var(--bg-secondary)] border-b border-[var(--border-color)]">
            <button
              onClick={() => setActiveTab("output")}
              className={`px-3 py-1 text-xs font-mono rounded ${
                activeTab === "output"
                  ? "bg-[var(--bg-card)] text-[var(--text-primary)] border border-[var(--border-color)]"
                  : "text-[var(--text-muted)]"
              }`}
            >
              Output Console
            </button>
            <button
              onClick={() => setActiveTab("bir")}
              className={`px-3 py-1 text-xs font-mono rounded ${
                activeTab === "bir"
                  ? "bg-[var(--bg-card)] text-[var(--text-primary)] border border-[var(--border-color)]"
                  : "text-[var(--text-muted)]"
              }`}
            >
              BIR SSA Dump
            </button>
            <button
              onClick={() => setActiveTab("llvm")}
              className={`px-3 py-1 text-xs font-mono rounded ${
                activeTab === "llvm"
                  ? "bg-[var(--bg-card)] text-[var(--text-primary)] border border-[var(--border-color)]"
                  : "text-[var(--text-muted)]"
              }`}
            >
              LLVM IR
            </button>
          </div>

          {/* Tab Content */}
          <div className="p-4 flex-1 font-mono text-xs overflow-auto leading-relaxed">
            {activeTab === "output" && <pre>{output}</pre>}
            {activeTab === "bir" && (
              <pre>{`%0 = alloc tensor<f32, [128, 64]>
%1 = alloc tensor<f32, [64, 32]>
%2 = matmul %0, %1 : (tensor<f32, [128, 64]>, tensor<f32, [64, 32]>) -> tensor<f32, [128, 32]>
ret %2`}</pre>
            )}
            {activeTab === "llvm" && (
              <pre>{`define i32 @main() {
entry:
  %call = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([32 x i8], [32 x i8]* @.str, i64 0, i64 0))
  ret i32 0
}`}</pre>
            )}
          </div>
        </div>
      </div>
    </Container>
  );
}
