blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://blyx-lang.space
    about: Please ask and answer questions about Blyx on the community site.
  - name: Feature Request
    url: https://github.com/Blyx-lang-space/blyx/issues
    about: Please discuss Blyx language feature requests in the issue tracker.
  - name: Clippy Bug
    url: https://github.com/Blyx-lang-space/blyx/issues/new/choose
    about: Please report Blyx linter bugs such as false positives in the issue tracker.
